spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: JWT-Auth
  jwt:
    secret: ${JWT_SECRET}  # To register this key, create a .env file at the root of the project with
                          # JWT_SECRET=value_of_the_key. Do not add this .env file to git
    accessTokenExpiration : 900
    refreshTokenExpiration: 604800
springdoc:
  override-with-generic-response: false